In [2]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

In [3]:
df = pd.read_csv('dpqa_fixed_lr.csv', index_col='Step')

In [4]:
df.columns

Index(['algorithm: 20-PQA - suboptimality',
       'algorithm: 20-PQA - suboptimality__MIN',
       'algorithm: 20-PQA - suboptimality__MAX',
       'algorithm: 15-PQA - suboptimality',
       'algorithm: 15-PQA - suboptimality__MIN',
       'algorithm: 15-PQA - suboptimality__MAX',
       'algorithm: 10-PQA - suboptimality',
       'algorithm: 10-PQA - suboptimality__MIN',
       'algorithm: 10-PQA - suboptimality__MAX',
       'algorithm: 5-PQA - suboptimality',
       'algorithm: 5-PQA - suboptimality__MIN',
       'algorithm: 5-PQA - suboptimality__MAX',
       'algorithm: 1-PQA - suboptimality',
       'algorithm: 1-PQA - suboptimality__MIN',
       'algorithm: 1-PQA - suboptimality__MAX'],
      dtype='object')

In [5]:
cols = [c for c in df.columns if '_M' not in c]
cols

['algorithm: 20-PQA - suboptimality',
 'algorithm: 15-PQA - suboptimality',
 'algorithm: 10-PQA - suboptimality',
 'algorithm: 5-PQA - suboptimality',
 'algorithm: 1-PQA - suboptimality']

In [6]:
df = df[cols]

In [7]:
df

,algorithm: 20-PQA - suboptimality,algorithm: 15-PQA - suboptimality,algorithm: 10-PQA - suboptimality,algorithm: 5-PQA - suboptimality,algorithm: 1-PQA - suboptimality
Step,,,,,
0,0.517446,0.517446,0.517446,0.517446,0.517446
1,0.517442,0.517442,0.517442,0.517442,0.517442
2,0.517438,0.517438,0.517438,0.517438,0.517438
3,0.517434,0.517434,0.517434,0.517434,0.517434
4,0.517430,0.517430,0.517430,0.517430,0.517430
...,...,...,...,...,...
195,0.000000,0.000000,0.000000,0.000000,0.000000
196,0.000000,0.000000,0.000000,0.000000,0.000000
197,0.000000,0.000000,0.000000,0.000000,0.000000
198,0.000000,0.000000,0.000000,0.000000,0.000000
199,0.000000,0.000000,0.000000,0.000000,0.000000

In [8]:
df.columns

Index(['algorithm: 20-PQA - suboptimality',
       'algorithm: 15-PQA - suboptimality',
       'algorithm: 10-PQA - suboptimality', 'algorithm: 5-PQA - suboptimality',
       'algorithm: 1-PQA - suboptimality'],
      dtype='object')

In [9]:
df = df.rename(columns={col: col[len('algorithm: '): -len(' - suboptimality')] for col in df.columns})
df

        20-PQA    15-PQA    10-PQA     5-PQA     1-PQA
Step
0     0.517446  0.517446  0.517446  0.517446  0.517446
1     0.517442  0.517442  0.517442  0.517442  0.517442
2     0.517438  0.517438  0.517438  0.517438  0.517438
3     0.517434  0.517434  0.517434  0.517434  0.517434
4     0.517430  0.517430  0.517430  0.517430  0.517430
...        ...       ...       ...       ...       ...
195   0.000000  0.000000  0.000000  0.000000  0.000000
196   0.000000  0.000000  0.000000  0.000000  0.000000
197   0.000000  0.000000  0.000000  0.000000  0.000000
198   0.000000  0.000000  0.000000  0.000000  0.000000
199   0.000000  0.000000  0.000000  0.000000  0.000000

[200 rows x 5 columns]

In [11]:
df.to_csv('dpqa_fixed_lr.csv', index=True)

In [12]:
stds = df.std(axis=0)

20-PQA    0.120262
15-PQA    0.129610
10-PQA    0.142325
5-PQA     0.163330
1-PQA     0.188271
dtype: float64